name: Deploy CDK

on:
  push:
    branches:
      - actions      

jobs:
  deploy:
    runs-on: 'self-hosted'
    steps:    
    - uses: actions/checkout@v2    

    - name: Deploy CDK app
      run: cdk deploy --require-approval never --all